script:
  - cd sprint_5
  - java -version
  - javac -version
  - java -jar ./tools/plantuml.jar -Tpng -o ./srcdoc/diag0.puml
  - python -V
  - python ./tools/asciidoc-8.6.9/asciidoc.py --version
  - python ./tools/asciidoc-8.6.9/asciidoc.py -a iconsdir=./tools/asciidoc-8.6.9/images/icons -o ./srcdoc/docUtilisateur.html ./srcdoc/docUtilisateur.txt